### ISSUE TITLE
Changelog is committed after the tag

### ISSUE THREAD

**Issue by dhinus** [FrancescoCioria/smooth-release#53]
At the moment, smooth-release generates two commits, the first with the version bump, the second one with the updated changelog. The git tag for the release is pointing to the first one, where the changelog has not been updated yet.

Example:
```
* d39311f (HEAD -> master, origin/master) Update CHANGELOG.md
* 79ec628 (tag: v0.4.1) 0.4.1
```

Ideally smooth-release should generate a single commit including both the version bump and the changelog update, and point the git tag to that commit.

**Comment by FrancescoCioria** [comment]
SPECS:
`npm-version` should update `package.json` without adding a commit nor a tag
`changelog` should update `CHANGELOG.md` without adding a commit
After these two scripts and **before** `gh-release` (which requires GitHub tags to up-to-date) run a new task `commitAndPush` which:
- creates a commit with changes named `Update CHANGELOG.md` if version was not increased or as the new version otherwise
- push changes and tags (if any) to GitHub
