### ISSUE TITLE
how does it compare to standard-version?

### ISSUE THREAD

**Issue by vesparny** [FrancescoCioria/smooth-release#94]
Hi,
thanks for sharing this project.

I've been using [standard-release](https://github.com/conventional-changelog/standard-version), and was wondering how does your project differ from it.

thanks

**Comment by gabro** [comment]
The first big difference I see is that smooth-release uses GitHub issue (or optionally pull request) titles as the source for the CHANGELOG entries.

standard-release (and many other similar projects) uses the git commit messages instead.

We didn't intent to force ourself to use squash merge commits and a specific format for commit messages, since it felt too cumbersome to enforce and maintain.

Issues/PRs titles usually already provide a descriptive message of the feature/bug, and they're easier to change if needed. So far, it worked great for us!

@FrancescoCioria can surely provide more details, but that is surely a big point of difference.

**Comment by gabro** [comment]
Plus, smooth-release takes care of many other things in addition to the versioning of the package, including:

- pushing the package to npm
- pushing a tag with a matching release on GitHub
- committing and publishing the CHANGELOG

You can configure it to run only some of the steps, but ideally it does everything that can be automated in a release process, preventing common mistakes due to manual procedure.

**Comment by vesparny** [comment]
@gabro thanks for the clear explanation.
I'll dig into the code as soon as I'll have some spare time 👍

**Comment by gabro** [comment]
Let me know if you have any other questions, I'm closing this in the meanwhile!
